# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(['cvkpy0.1.1.py'],
             pathex=[],
             binaries=[],
			 datas=[
             ('vkImage0_0_0.png','.'),
             ('vkImage1_0_0.png','.'),
             ('vkImage1_0_1.png','.'),
             ('vkImage1_1_1.png','.'),
             ('vkImage2_0_0.png','.'),
             ('vkImage2_0_1.png','.'),
             ('vkImage2_1_1.png','.'),
             ('vkImagep0.png','.'),
             ('vkImagep1.png','.'),
             ('vkImagep2.png','.'),
             ('vkImage0_0.png','.'),
             ('vkImage-1_1.png','.'),
             ('vkImage-1_2.png','.'),
             ('vkImage1_1.png','.'),
             ('vkImage1_2.png','.'),
             ('vkImage2_1.png','.'),
             ('vkImage2_2.png','.'),
             ('vkImage3_1.png','.'),
             ('vkImage3_2.png','.'),
             ('vkImage4_1.png','.'),
             ('vkImage4_2.png','.'),
             ('vkImage5_1.png','.'),
             ('vkImage5_2.png','.'),
             ('vkImage6_1.png','.'),
             ('vkImage6_2.png','.'),
             ('vkImage7_1.png','.'),
             ('vkImage7_2.png','.'),
             ('vkImage8_1.png','.'),
             ('vkImage8_2.png','.'),
             ('vkImage9_1.png','.'),
             ('vkImage9_2.png','.'),
             ('vkImage10_1.png','.'),
             ('vkImage10_2.png','.'),
             ('vkImage11_1.png','.'),
             ('vkImage11_2.png','.'),
             ('vkImage12_1.png','.'),
             ('vkImage12_2.png','.'),
             ('vkImage13_1.png','.'),
             ('vkImage13_2.png','.'),
             ('vkImage14_1.png','.'),
             ('vkImage14_2.png','.'),
             ('vkImage15_1.png','.'),
             ('vkImage15_2.png','.'),
             ('vkImage16_1.png','.'),
             ('vkImage16_2.png','.'),
             ('vkImage17_1.png','.'),
             ('vkImage17_2.png','.'),
             ('vkImage18_1.png','.'),
             ('vkImage18_2.png','.'),
             ('vkImage19_1.png','.'),
             ('vkImage19_2.png','.'),
             ('lose.png','.'),
             ('win.png','.'),
             ('first.png','.'),
             ('second.png','.'),
             ('cvkso0.1.7.so','.'),
             ('undo.png','.'),
             ('change.png','.'),
             ('boardline.png','.')],
             hiddenimports=[],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,  
          [],
          name='科摩多龍棋cpy0.1.1版',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None , icon='kmdlico.ico')
