# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(['pyvk_alpha0.9.15.py'],
             pathex=['C:\vk\pyvk_alpha0.9.15'],
             binaries=[],
             datas=[
             ('image\\background\\vkImage0.png','image\\background'),
             ('image\\background\\vkImage1.png','image\\background'),
             ('image\\background\\vkImage2.png','image\\background'),
             ('image\\background\\vkImage3.png','image\\background'),
             ('image\\background\\vkImage4.png','image\\background'),
             ('image\\background\\vkImage5.png','image\\background'),
             ('image\\background\\vkImage6.png','image\\background'),
             ('image\\background\\vkImage7.png','image\\background'),
             ('image\\background\\vkImage8.png','image\\background'),
             ('image\\background\\vkImage9.png','image\\background'),
             ('image\\background\\vkImage10.png','image\\background'),
             ('image\\chess\\vkImage0_0.png','image\\chess'),
             ('image\\chess\\vkImage-1_1.png','image\\chess'),
             ('image\\chess\\vkImage-1_2.png','image\\chess'),
             ('image\\chess\\vkImage1_1.png','image\\chess'),
             ('image\\chess\\vkImage1_2.png','image\\chess'),
             ('image\\chess\\vkImage2_1.png','image\\chess'),
             ('image\\chess\\vkImage2_2.png','image\\chess'),
             ('image\\chess\\vkImage3_1.png','image\\chess'),
             ('image\\chess\\vkImage3_2.png','image\\chess'),
             ('image\\chess\\vkImage4_1.png','image\\chess'),
             ('image\\chess\\vkImage4_2.png','image\\chess'),
             ('image\\chess\\vkImage5_1.png','image\\chess'),
             ('image\\chess\\vkImage5_2.png','image\\chess'),
             ('image\\chess\\vkImage6_1.png','image\\chess'),
             ('image\\chess\\vkImage6_2.png','image\\chess'),
             ('image\\chess\\vkImage7_1.png','image\\chess'),
             ('image\\chess\\vkImage7_2.png','image\\chess'),
             ('image\\chess\\vkImage8_1.png','image\\chess'),
             ('image\\chess\\vkImage8_2.png','image\\chess'),
             ('image\\chess\\vkImage9_1.png','image\\chess'),
             ('image\\chess\\vkImage9_2.png','image\\chess'),
             ('image\\chess\\vkImage10_1.png','image\\chess'),
             ('image\\chess\\vkImage10_2.png','image\\chess'),
             ('image\\chess\\vkImage11_1.png','image\\chess'),
             ('image\\chess\\vkImage11_2.png','image\\chess'),
             ('image\\chess\\vkImage12_1.png','image\\chess'),
             ('image\\chess\\vkImage12_2.png','image\\chess'),
             ('image\\chess\\vkImage13_1.png','image\\chess'),
             ('image\\chess\\vkImage13_2.png','image\\chess'),
             ('image\\chess\\vkImage14_1.png','image\\chess'),
             ('image\\chess\\vkImage14_2.png','image\\chess'),
             ('image\\chess\\vkImage15_1.png','image\\chess'),
             ('image\\chess\\vkImage15_2.png','image\\chess'),
             ('image\\chess\\vkImage16_1.png','image\\chess'),
             ('image\\chess\\vkImage16_2.png','image\\chess'),
             ('image\\chess\\vkImage17_1.png','image\\chess'),
             ('image\\chess\\vkImage17_2.png','image\\chess'),
             ('image\\chess\\vkImage18_1.png','image\\chess'),
             ('image\\chess\\vkImage18_2.png','image\\chess'),
             ('image\\chess\\vkImage19_1.png','image\\chess'),
             ('image\\chess\\vkImage19_2.png','image\\chess'),
             ('image\\other\\lose.png','image\\other'),
             ('image\\other\\win.png','image\\other'),
             ('image\\other\\first.png','image\\other'),
             ('image\\other\\second.png','image\\other'),
             ('image\\other\\undo.png','image\\other'),
             ('image\\other\\change.png','image\\other')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='科摩多龍棋0.9.15',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False , icon='kmdlico.ico')
